#!/usr/bin/env python3
import os
import subprocess
import venv
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"

if _VENV_DIR.exists():
    context = venv.EnvBuilder().ensure_directories(_VENV_DIR)
    python_exe = context.env_exe
else:
    python_exe = "python3"

env = os.environ.copy()
env["PYTHONPATH"] = str(_PROGRAM_DIR / "src")
subprocess.check_call(
    [python_exe, "-m", "unittest", "discover", "-s", "tests", "-v"],
    cwd=_PROGRAM_DIR,
    env=env,
)
