[mypy]

[mypy-pyring_buffer.*]
ignore_missing_imports = True

[mypy-webrtc_noise_gain.*]
ignore_missing_imports = True

[mypy-nemo.*]
ignore_missing_imports = True

[mypy-ovos_number_parser.*]
ignore_missing_imports = True

[mypy-ovos_date_parser.*]
ignore_missing_imports = True
